
name: add-issues-to-octue-board

on:
  issues:
    types: [opened, reopened]

jobs:

  add-to-board:
    runs-on: ubuntu-latest
    steps:
      - uses: monry/actions-add-issue-to-project@v1
        with:
          # Personal Access Token with `repo`, `org:read` and `org:write` granted
          github-token: ${{ secrets.PROJECT_AUTOMATION_GITHUB_TOKEN }}
          project-owner: 'octue'
          project-number: 22
          issue-id: ${{ github.event.issue.node_id }}
