name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - labels.yml
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          prune: true
          repository: |
              octue/.github
              octue/amy
              octue/automan
              octue/conventional-commits
              octue/django-twined
              octue/django-dag-cte
              octue/django-gcp
              octue/es-flow
              octue/example-service-cloud-run
              octue/hex
              octue/how-tos
              octue/octue-gcp
              octue/octue-sdk-python
              octue/octue-sdk-cpp
              octue/openfast-docker
              octue/planex-site
              octue/strands
              octue/timper
              octue/twined
              octue/yuriy-foil
              octue/tpast
              
          token: ${{ secrets.PROJECT_AUTOMATION_GITHUB_TOKEN }}
