name: update-pull-request

on:
  pull_request:

jobs:
  description:
    uses: ./.github/workflows/reusable-update-pull-request.yml
    secrets:
      github-token: ${{ secrets.PROJECT_AUTOMATION_GITHUB_TOKEN_2 }}
