name: Synchronise Workflows

# Synchronise both when a file is changed in this repo, and daily to avoid anything getting out of sync
# in the child repositories
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  workflow_sync:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Local Repository
        uses: actions/checkout@v2
      - name: Sync Workflows
        uses: adrianjost/files-sync-action@master
        with:
          COMMIT_MESSAGE: "OPS: Update workflow from octue/.github skipci"
          SRC_ROOT: /synced-workflows/
          TARGET_ROOT: /.github/workflows/
          FILE_PATTERNS: |-
            ^synced-add-issues-to-octue-board\.yaml$
          TARGET_REPOS: |-
            octue/amy
            octue/amy-fibres
            octue/amy-ui
            octue/octue-sdk-python
            octue/planex-site
            octue/twined
          GITHUB_TOKEN: ${{ secrets.PROJECT_AUTOMATION_GITHUB_TOKEN }}
